-- =====================================================================
--  IRON DOCTRINE — Phase 1, file #3: DATA MIGRATION (from Notion)
--  Run in: Supabase Dashboard -> SQL Editor -> New query -> Run
--  Run AFTER 001_schema.sql and 002_rls.sql.
--
--  Linking strategy: child rows resolve their parent by NATURAL KEY via
--  subquery (coaches.email, clients.notion_id, exercises.name_en), so we
--  never hand-manage UUIDs. Service role runs this, bypassing RLS.
--
--  NOTE: all clients are TEST data -> tagged is_test = true. Purge later
--  with:  delete from clients where is_test = true;  (cascades children)
-- =====================================================================

-- Tag column for easy test-data purge (idempotent).
alter table clients add column if not exists is_test boolean not null default false;

-- ---------------------------------------------------------------------
--  COACHES — you, the platform admin. Everything hangs off this row.
-- ---------------------------------------------------------------------
insert into coaches (name, email, role, status)
values ('Patrik Šebest', 'sebestpatrik@gmail.com', 'platform_admin', 'active')
on conflict do nothing;


-- ---------------------------------------------------------------------
--  CLIENTS — all test data (is_test = true), owned by the platform admin.
-- ---------------------------------------------------------------------
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('38e1a67a-924d-813a-85e7-ec387affcfd0', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Test Onboard', 'sebestpatrik+onboard@gmail.com', 'Czech', 'Build muscle', 'Active', '2026-06-29', true, '2026-06-29', '2026-06-28', NULL, NULL, true);
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('38e1a67a-924d-8191-9cc4-e4f1602daef5', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Barbora Střelcová', 'Barastrelcova@seznam.cz', 'Czech', 'Lose fat', 'Active', '2026-06-29', true, '2026-06-29', '2026-06-28', NULL, NULL, true);
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('38e1a67a-924d-81b5-85a3-cab6940f070b', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Invite Test', 'sebbabest@gmail.com', 'Czech', 'Build muscle', 'Active', '2026-06-29', true, '2026-06-29', '2026-06-28', NULL, NULL, true);
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('38f1a67a-924d-815b-aed6-d13bc9afb84a', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Michaela Paslerová', 'michaelacerhova@seznam.cz', 'Czech', 'Build muscle', 'Active', '2026-06-30', true, '2026-06-30', '2026-06-28', NULL, NULL, true);
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('3891a67a-924d-81a1-ae44-efe23f1d3a9e', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Jan Procházka (CZ Test)', 'sebestpatrik@gmail.com', 'English', 'Build muscle', 'Active', '2026-06-24', true, '2026-06-29', '2026-06-28', 'Online Coaching', '32 let · 82 kg · náběr svalové hmoty. Český testovací klient — celá stránka v češtině.', true);
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('38e1a67a-924d-8135-8e42-e0d31d1fd6a6', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Tereza Dummy (TEST)', 'tereza.dummy.test@example.com', 'English', 'Lose fat', 'Active', '2026-04-15', false, NULL, NULL, NULL, NULL, true);
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('38e1a67a-924d-819d-9c22-d46687e15f60', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Petr Dummy (TEST)', 'petr.dummy.test@example.com', 'Czech', 'Strength', 'Paused', '2026-03-20', false, NULL, NULL, NULL, NULL, true);
insert into clients (notion_id, coach_id, name, email, language, primary_goal, status, start_date, consent_given, consent_date, policy_version, service, notes, is_test)
values ('38e1a67a-924d-81e5-9d49-d0739870d7d9', (select id from coaches where email='sebestpatrik@gmail.com' and role='platform_admin' limit 1), 'Marek Dummy (TEST)', 'marek.dummy.test@example.com', 'Czech', 'Build muscle', 'Active', '2026-05-01', false, NULL, NULL, NULL, NULL, true);

-- ---------------------------------------------------------------------
--  EXERCISES — your curated bilingual library (REAL content, kept).
-- ---------------------------------------------------------------------
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Lying Leg Curl', 'Zakopávání vleže', 'Hamstrings', 'Isolation', 'Machine', 'Curl heels to glutes, squeeze, control back.', 'Zakop paty k hýždím, zatni, kontrolovaně zpět.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Smith Machine Incline Press', 'Tlak na šikmé lavici na Smithově stroji', 'Chest', 'Horizontal Push', 'Smith', 'Bench ~30° in the bar path, bar to upper chest, controlled press.', 'Lavice ~30° v dráze osy, činka k horní části hrudníku, kontrolovaný tlak.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Hip Abduction Machine', 'Roznožování ve stroji (abduktory)', 'Glutes', 'Isolation', 'Machine', 'Slight lean forward, push knees out, squeeze glutes.', 'Mírný předklon, roznož kolena, zatni hýždě.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('EZ-Bar Curl', 'Bicepsový zdvih s EZ osou', 'Biceps', 'Isolation', 'EZ-bar', 'EZ grip, elbows at sides, smooth curl.', 'Úchop na EZ ose, lokty u těla, plynulý zdvih.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Lat Pulldown', 'Stahování horní kladky nadhmatem', 'Lats', 'Vertical Pull', 'Cable', 'Slight lean back, bar to upper chest, elbows down and in.', 'Mírný záklon, hrazdu k horní části hrudníku, lokty dolů a dovnitř.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Lateral Raise', 'Upažování s jednoručkami', 'Side Delts', 'Isolation', 'Dumbbell', 'Soft elbows, lead with elbows, raise to shoulder height.', 'Mírně pokrčené lokty, veď lokty, zvedej do výše ramen.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Glute Bridge', 'Most (zved ání pánve)', 'Glutes', 'Hinge', 'Barbell', 'Back on floor, drive hips up, squeeze glutes at top.', 'Záda na zemi, vytlač boky, zatni hýždě nahoře.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Romanian Deadlift', 'Rumunský mrtvý tah', 'Hamstrings', 'Hinge', 'Barbell', 'Soft knees, push hips back, bar close, feel the hamstrings.', 'Mírně pokrčená kolena, boky vzad, osa u těla, cítit hamstringy.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Hanging Leg Raise', 'Zvedání nohou ve vise', 'Core', 'Core', 'Bodyweight', 'No swing, curl pelvis up, control down.', 'Bez hmitu, podsáď pánev nahoru, kontrolovaně dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Overhead Dumbbell Extension', 'Zapažování s jednoručkou nad hlavou', 'Triceps', 'Isolation', 'Dumbbell', 'Both hands under the bell, lower behind head, extend.', 'Obě ruce pod hlavu činky, spusť za hlavu, propni.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Pull-up', 'Shyby nadhmatem', 'Lats', 'Vertical Pull', 'Bodyweight', 'Full hang, drive elbows down to ribs, chest toward bar.', 'Plný vis, tahni lokty dolů k žebrům, hrudník k hrazdě.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Incline Dumbbell Curl', 'Bicepsový zdvih na šikmé lavici', 'Biceps', 'Isolation', 'Dumbbell', 'Lie back, arms hang, curl with elbows still.', 'Opři se vzad, paže visí, zvedej s lokty na místě.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Concentration Curl', 'Koncentrovaný zdvih', 'Biceps', 'Isolation', 'Dumbbell', 'Elbow on inner thigh, squeeze hard at the top.', 'Loket opřený o stehno, zatni v horní pozici.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Cable Lateral Raise', 'Upažování na kladce (jednoruč)', 'Side Delts', 'Isolation', 'Cable', 'Cable behind body, raise smoothly, constant tension.', 'Kladka za tělem, upažuj plynule, stálé napětí.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Close-Grip Pulldown', 'Stahování horní kladky úzkým úchopem', 'Lats', 'Vertical Pull', 'Cable', 'Neutral close grip, elbows to hips, full stretch up top.', 'Neutrální úzký úchop, lokty k bokům, plné protažení nahoře.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Leg Press', 'Leg press (tlak nohama)', 'Quads', 'Squat', 'Machine', 'Feet mid-platform, lower to ~90°, don''t lock hard.', 'Chodidla na středu plošiny, spusť do ~90°, neprodpínej tvrdě.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Front Raise', 'Předpažování s jednoručkami', 'Front Delts', 'Isolation', 'Dumbbell', 'Raise to shoulder height, no swing, control down.', 'Předpažuj do výše ramen, bez hmitu, kontrolovaně dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Dumbbell Curl', 'Bicepsový zdvih s jednoručkami', 'Biceps', 'Isolation', 'Dumbbell', 'Alternate arms, supinate wrist at the top.', 'Střídej paže, nahoře vytoč zápěstí (supinace).');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Cable Crunch', 'Zkracovačky na kladce', 'Core', 'Core', 'Cable', 'Round spine down, crunch with abs not arms.', 'Zakulať páteř dolů, krč břichem, ne pažemi.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Cable Curl', 'Bicepsový zdvih na spodní kladce', 'Biceps', 'Isolation', 'Cable', 'Constant tension, elbows pinned, control down.', 'Stálé napětí, lokty u těla, kontrolovaně dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Overhead Cable Extension', 'Zapažování na kladce nad hlavou', 'Triceps', 'Isolation', 'Cable', 'Elbows high, extend overhead, feel the stretch.', 'Lokty vysoko, propni nad hlavou, cítit protažení.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Copenhagen Plank', 'Kodaňské prkno (adduktory)', 'Adductors', 'Core', 'Bodyweight', 'Top leg on bench, hold hips up, brace inner thigh.', 'Horní noha na lavici, drž pánev nahoře, zpevni vnitřní stehno.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Farmer''s Carry', 'Farmářská chůze', 'Forearms', 'Carry', 'Dumbbell', 'Heavy, tall posture, firm grip, walk controlled.', 'Těžké činky, vzpřímený postoj, pevný úchop, kontrolovaná chůze.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Standing Calf Raise', 'Výpony ve stoje', 'Calves', 'Isolation', 'Machine', 'Full stretch at bottom, rise onto toes, pause at top.', 'Plné protažení dole, vytáhni na špičky, pauza nahoře.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Face Pull', 'Přitahování ke tváři na kladce', 'Rear Delts', 'Horizontal Pull', 'Cable', 'Rope to forehead, elbows high, rotate hands back.', 'Lano k čelu, lokty vysoko, vytoč ruce vzad.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('One-Arm Dumbbell Row', 'Veslování s jednoručkou (jednoruč)', 'Upper Back', 'Horizontal Pull', 'Dumbbell', 'Support on bench, pull dumbbell to hip, control down.', 'Opora o lavici, tahni jednoručku k boku, kontrolovaně dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Donkey Calf Raise', 'Oslí výpony', 'Calves', 'Isolation', 'Bodyweight', 'Bent over, load on hips, full stretch and rise.', 'Předklon, zátěž na bocích, plné protažení a výpon.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Skull Crusher', 'Francouzský tlak vleže (skull crusher)', 'Triceps', 'Isolation', 'EZ-bar', 'Lower to forehead, elbows still, extend up.', 'Spusť k čelu, lokty na místě, propni nahoru.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Plank', 'Prkno (plank)', 'Core', 'Core', 'Bodyweight', 'Straight line, brace abs, don''t let hips sag.', 'Rovná přímka, zpevni břicho, nepropínej se v bocích.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Push-up', 'Kliky', 'Chest', 'Horizontal Push', 'Bodyweight', 'Body in a straight line, elbows ~45°, full range, brace the core.', 'Tělo v jedné přímce, lokty cca 45°, plný rozsah, zpevni střed těla.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Low-to-High Cable Fly', 'Rozpažování na spodních kladkách (zdola nahoru)', 'Chest', 'Isolation', 'Cable', 'Pulleys low, sweep up and in to nose height, squeeze upper chest.', 'Kladky dole, veď nahoru a dovnitř do výše nosu, zatni horní část prsou.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Preacher Curl', 'Bicepsový zdvih na Scottově lavici', 'Biceps', 'Isolation', 'EZ-bar', 'Arms on pad, full stretch at bottom, no hard lockout.', 'Paže opřené, plné protažení dole, nepropínej do zámku.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Incline Dumbbell Fly', 'Rozpažování s jednoručkami na šikmé lavici', 'Chest', 'Isolation', 'Dumbbell', 'Bench ~30°, wide arc, feel the upper-chest stretch.', 'Lavice ~30°, široký oblouk, cítit protažení horní části prsou.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Decline Barbell Bench Press', 'Tlak s velkou činkou na záporné lavici', 'Chest', 'Horizontal Push', 'Barbell', 'Bar to lower chest, elbows under the bar, controlled descent.', 'Činka k dolní části hrudníku, lokty pod osou, kontrolované spouštění.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Decline Sit-up', 'Sed-lehy na záporné lavici', 'Core', 'Core', 'Bodyweight', 'Controlled sit-up, roll the spine, no bouncing.', 'Kontrolovaný sed-leh, bedra plynule, nezhoupavej.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Flat Dumbbell Fly', 'Rozpažování s jednoručkami na rovné lavici', 'Chest', 'Isolation', 'Dumbbell', 'Soft elbow bend, open wide to a stretch, hug the weights back up.', 'Mírně pokrčené lokty, rozevři do protažení, „obejmi“ činky zpět nahoru.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Weighted Chest Dip', 'Bradla s důrazem na hrudník (s přídavnou zátěží)', 'Chest', 'Horizontal Push', 'Bodyweight', 'Lean torso forward, elbows slightly flared, dip to a chest stretch.', 'Trup mírně předkloň, lokty mírně od těla, spusť do protažení hrudníku.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Seated Cable Row', 'Veslování na spodní kladce vsedě', 'Upper Back', 'Horizontal Pull', 'Cable', 'Tall chest, pull to navel, blades back, no torso swing.', 'Hrudník vzhůru, tahni k pupku, lopatky vzad, bez hmitu trupem.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Rear Delt Fly', 'Rozpažování v předklonu (zadní delty)', 'Rear Delts', 'Isolation', 'Dumbbell', 'Hinge over, raise wide, lead with the pinkies.', 'Předklon, rozpažuj do široka, veď malíky vzhůru.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Overhead Press', 'Tlak nad hlavu s velkou činkou (vojenský tlak)', 'Front Delts', 'Vertical Push', 'Barbell', 'Brace, bar over mid-foot, press to lockout overhead.', 'Zpevni střed, osa nad středem chodidla, tlač do propnutí nad hlavou.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Barbell Bench Press', 'Tlak s velkou činkou na rovné lavici', 'Chest', 'Horizontal Push', 'Barbell', 'Shoulder blades retracted, slight arch, bar to lower chest, elbows ~45°.', 'Lopatky stažené k sobě, mírné prohnutí, činka k dolní části hrudníku, lokty cca 45°.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Incline Barbell Bench Press', 'Tlak s velkou činkou na šikmé lavici', 'Chest', 'Horizontal Push', 'Barbell', 'Bench ~30°, bar to upper chest, drive up and slightly back.', 'Lavice ~30°, činka k horní části hrudníku, tlač nahoru a mírně vzad.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Step-up', 'Výstupy na lavici', 'Quads', 'Lunge', 'Dumbbell', 'Whole foot on bench, drive through heel, no overshoot.', 'Celé chodidlo na lavici, tlač přes patu, nahoře nepřepadávej.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Back Squat', 'Dřep s velkou činkou (zadní)', 'Quads', 'Squat', 'Barbell', 'Brace, sit between hips, knees track toes, drive up.', 'Zpevni střed, sedni mezi boky, kolena ve směru špiček, vytlač vzhůru.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Cable Kickback', 'Zanožování na kladce', 'Glutes', 'Isolation', 'Cable', 'Cuff on ankle, kick back, squeeze the glute.', 'Manžeta na kotníku, zanož vzad, zatni hýždi.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Hammer Curl', 'Kladívkový zdvih', 'Biceps', 'Isolation', 'Dumbbell', 'Neutral grip (palms in), elbows at sides.', 'Neutrální úchop (dlaně k sobě), lokty u těla.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Dumbbell Shrug', 'Krčení ramen s jednoručkami', 'Traps', 'Isolation', 'Dumbbell', 'Dumbbells at sides, shrug up, squeeze and slow down.', 'Jednoručky podél těla, krč vzhůru, zatni a pomalu dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Seated Leg Curl', 'Zakopávání vsedě', 'Hamstrings', 'Isolation', 'Machine', 'Pull heels under seat, squeeze, slow return.', 'Stáhni paty pod sedák, zatni, pomalý návrat.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Triceps Pushdown (bar)', 'Stahování kladky na triceps (rovná hrazda)', 'Triceps', 'Isolation', 'Cable', 'Elbows fixed, extend fully, slow return.', 'Lokty fixní, propni úplně, pomalu zpět.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Good Morning', 'Předklony s činkou (good morning)', 'Hamstrings', 'Hinge', 'Barbell', 'Bar on back, hips back, flat back, rise through hamstrings.', 'Činka na zádech, boky vzad, rovná záda, vzpřim přes hamstringy.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Side Plank', 'Boční prkno', 'Core', 'Core', 'Bodyweight', 'Body in line, hips up, brace the side.', 'Tělo v přímce, boky vzhůru, zpevni bok.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Ab Wheel Rollout', 'Rollout s kolečkem', 'Core', 'Core', 'Bodyweight', 'Brace core, roll out without arching, pull back.', 'Zpevni střed, vyjeď vpřed bez prohnutí, přitáhni zpět.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Triceps Kickback', 'Zapažování v předklonu (kickback)', 'Triceps', 'Isolation', 'Dumbbell', 'Hinge, elbow high and fixed, extend back.', 'Předklon, loket vysoko a fixní, propni vzad.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Bulgarian Split Squat', 'Bulharský výpad (zadní noha na lavici)', 'Quads', 'Lunge', 'Dumbbell', 'Rear foot elevated, drop straight down, drive through front heel.', 'Zadní noha na lavici, klesej svisle dolů, tlač přes patu přední nohy.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Sumo Deadlift', 'Sumo mrtvý tah', 'Glutes', 'Hinge', 'Barbell', 'Wide stance, toes out, drive hips through.', 'Široký postoj, špičky ven, protlač boky vpřed.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Front Squat', 'Přední dřep', 'Quads', 'Squat', 'Barbell', 'Elbows high, upright torso, full depth.', 'Lokty vysoko, vzpřímený trup, plná hloubka.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Wrist Curl', 'Zdvih zápěstí (flexe)', 'Forearms', 'Isolation', 'Dumbbell', 'Forearms supported, curl wrists up, full range.', 'Předloktí opřená, krč zápěstí nahoru, plný rozsah.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Machine Row', 'Veslování ve stroji', 'Upper Back', 'Horizontal Pull', 'Machine', 'Chest tall, drive elbows back, full squeeze, slow return.', 'Hrudník vzhůru, lokty vzad, plné zatnutí, pomalý návrat.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Goblet Squat', 'Goblet dřep (s jednoručkou)', 'Quads', 'Squat', 'Dumbbell', 'Bell at chest, squat between knees, upright torso.', 'Činku u hrudníku, dřep mezi kolena, vzpřímený trup.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Triceps Dip', 'Bradla na triceps (vzpřímený trup)', 'Triceps', 'Vertical Push', 'Bodyweight', 'Torso upright, elbows back, dip and press up.', 'Trup vzpřímený, lokty vzad, spusť a vytlač.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Upright Row', 'Přitahování k bradě (široký úchop)', 'Side Delts', 'Vertical Pull', 'Barbell', 'Pull to chest height, elbows lead, no shrug.', 'Tahni do výše hrudníku, lokty vedou, bez krčení ramen.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Cable Woodchopper', 'Dřevorubec na kladce', 'Core', 'Rotation', 'Cable', 'Pull diagonally across body, rotate from torso, hips stable.', 'Táhni úhlopříčně přes tělo, otáčej z trupu, boky stabilní.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Glute Kickback Machine', 'Zanožování ve stroji', 'Glutes', 'Isolation', 'Machine', 'Torso supported, kick back controlled, squeeze at top.', 'Opora o trup, zanož kontrolovaně, zatni nahoře.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Leg Extension', 'Předkopávání (extenze kolen)', 'Quads', 'Isolation', 'Machine', 'Control up, squeeze at top, slow down.', 'Kontrolovaně nahoru, zatni nahoře, pomalu dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Cable Rear Delt Fly', 'Rozpažování na kladkách (zadní delty)', 'Rear Delts', 'Isolation', 'Cable', 'Cross cables, open back wide, constant tension.', 'Křížem přes tělo, rozpažuj vzad, stálé napětí.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Straight-Arm Pulldown', 'Stahování kladky s nataženými pažemi', 'Lats', 'Isolation', 'Cable', 'Arms long, sweep bar to thighs, feel the lats.', 'Paže natažené, veď hrazdu ke stehnům, cítit široký sval zádový.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Lying Leg Raise', 'Zvedání nohou vleže', 'Core', 'Core', 'Bodyweight', 'Low back down, raise legs, control down.', 'Bedra na zemi, zvedej nohy, kontrolovaně dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Seated Dumbbell Press', 'Tlak s jednoručkami nad hlavu vsedě', 'Front Delts', 'Vertical Push', 'Dumbbell', 'Back supported, press overhead, lower to ear level.', 'Záda o opěrku, tlač nad hlavu, dolů do úrovně uší.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Inverted Row', 'Australské shyby (veslování ve vise)', 'Upper Back', 'Horizontal Pull', 'Bodyweight', 'Body rigid, pull chest to bar, squeeze blades.', 'Tělo zpevněné, tahni hrudník k tyči, stáhni lopatky.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('High-to-Low Cable Fly', 'Rozpažování na horních kladkách (shora dolů)', 'Chest', 'Isolation', 'Cable', 'Pulleys high, sweep down and in to the waist, squeeze lower chest.', 'Kladky nahoře, veď dolů a dovnitř k pasu, zatni dolní část prsou.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Barbell Curl', 'Bicepsový zdvih s velkou činkou', 'Biceps', 'Isolation', 'Barbell', 'Elbows pinned, curl without swing, squeeze at top.', 'Lokty u těla, zvedej bez hmitu, nahoře zatni.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Nordic Curl', 'Nordické zakopávání', 'Hamstrings', 'Isolation', 'Bodyweight', 'Ankles anchored, lower slowly forward, brake with hamstrings.', 'Kotníky fixní, klesej pomalu vpřed, brzdi hamstringy.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Machine Lateral Raise', 'Upažování ve stroji', 'Side Delts', 'Isolation', 'Machine', 'Elbows against pads, raise to shoulder height, slow down.', 'Lokty proti opěrkám, zvedej do výše ramen, pomalu dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Reverse Curl', 'Bicepsový zdvih nadhmatem', 'Forearms', 'Isolation', 'EZ-bar', 'Overhand grip, elbows at sides, curl without swing.', 'Nadhmat, lokty u těla, zvedej bez hmitu.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Hip Thrust', 'Hip thrust (zved ání pánve s činkou)', 'Glutes', 'Hinge', 'Barbell', 'Upper back on bench, chin tucked, drive hips up, squeeze glutes.', 'Horní záda o lavici, brada zasunutá, vytlač boky vzhůru, zatni hýždi.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Machine Chest Press', 'Tlak na prsa ve stroji', 'Chest', 'Horizontal Push', 'Machine', 'Handles at mid-chest, press without harsh lockout, control the return.', 'Madla ve výši středu hrudníku, tlač bez tvrdého propnutí, kontroluj návrat.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Seated Calf Raise', 'Výpony vsedě', 'Calves', 'Isolation', 'Machine', 'Knees fixed, full range, slow down.', 'Kolena fixní, plný rozsah, pomalu dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Stiff-Leg Deadlift', 'Mrtvý tah s napjatýma nohama', 'Hamstrings', 'Hinge', 'Barbell', 'Near-straight knees, hips back, lower to a stretch.', 'Téměř napjatá kolena, boky vzad, spusť do protažení.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Rack Pull', 'Mrtvý tah z podstavců (rack pull)', 'Upper Back', 'Hinge', 'Barbell', 'Bar just below knees, brace, pull and lock hips.', 'Osa těsně pod kolena, zpevni střed, táhni a propni boky.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Chest-Supported Row', 'Veslování s oporou hrudníku', 'Upper Back', 'Horizontal Pull', 'Machine', 'Chest on pad, row to ribs, pause and squeeze.', 'Hrudník o opěrku, tahni k žebrům, pauza a zatni.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Frog Pump', 'Žabí zved ání pánve', 'Glutes', 'Isolation', 'Bodyweight', 'Soles together, knees out, drive hips up and squeeze.', 'Chodidla k sobě, kolena ven, vytlač boky a zatni.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Hip Adduction Machine', 'Stahování ve stroji (adduktory)', 'Adductors', 'Isolation', 'Machine', 'Draw knees together, squeeze, control back.', 'Stáhni kolena k sobě, zatni, kontrolovaně zpět.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Flat Dumbbell Press', 'Tlak s jednoručkami na rovné lavici', 'Chest', 'Horizontal Push', 'Dumbbell', 'Dumbbells over chest, lower to a stretch, press up and together.', 'Jednoručky nad hrudníkem, spusť do protažení, tlač nahoru a k sobě.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('T-Bar Row', 'T-bar veslování', 'Upper Back', 'Horizontal Pull', 'Barbell', 'Hinge, pull handles to chest, drive elbows back.', 'Předklon, tahni madla k hrudníku, lokty vzad.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Hack Squat', 'Hack dřep (ve stroji)', 'Quads', 'Squat', 'Machine', 'Back on pad, feet lower on platform, squat deep.', 'Záda o opěrku, chodidla níž na plošině, hluboký dřep.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Cable Fly (mid)', 'Rozpažování na kladkách (svedení)', 'Chest', 'Isolation', 'Cable', 'Pulleys at chest height, soft elbows, squeeze hands together in front.', 'Kladky ve výši hrudníku, lokty mírně pokrčené, sveď ruce před tělem k sobě.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Dumbbell Pullover', 'Přetahy s jednoručkou (pullover)', 'Lats', 'Isolation', 'Dumbbell', 'Stretch overhead, pull over to chest with lats, soft elbows.', 'Protazení za hlavou, přetáhni nad hrudník zády, lokty mírně pokrčené.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Conventional Deadlift', 'Mrtvý tah (klasický)', 'Hamstrings', 'Hinge', 'Barbell', 'Bar over mid-foot, flat back, push the floor away, lock hips.', 'Osa nad středem chodidla, rovná záda, odtlač podlahu, propni boky.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Close-Grip Bench Press', 'Tlak na lavici úzkým úchopem', 'Triceps', 'Horizontal Push', 'Barbell', 'Hands shoulder-width, elbows tucked, bar to lower chest.', 'Ruce na šíři ramen, lokty u těla, osa k dolnímu hrudníku.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Chin-up', 'Shyby podhmatem', 'Lats', 'Vertical Pull', 'Bodyweight', 'Underhand grip, lead with the chest, squeeze at the top.', 'Podhmat, veď hrudníkem, zatni nahoře.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Pendlay Row', 'Pendlay veslování (z podlahy)', 'Upper Back', 'Horizontal Pull', 'Barbell', 'Flat back, explosive pull to chest, reset on floor each rep.', 'Rovná záda, výbušný tah k hrudníku, každé opakování z podlahy.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Walking Lunge', 'Výpady v chůzi', 'Quads', 'Lunge', 'Dumbbell', 'Long stride, rear knee to floor, drive through heel.', 'Dlouhý krok, zadní koleno k zemi, tlač přes patu.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Incline Dumbbell Press', 'Tlak s jednoručkami na šikmé lavici', 'Chest', 'Horizontal Push', 'Dumbbell', 'Bench ~30°, elbows ~45°, press up and slightly in.', 'Lavice ~30°, lokty cca 45°, tlač nahoru a mírně dovnitř.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Barbell Shrug', 'Krčení ramen s velkou činkou', 'Traps', 'Isolation', 'Barbell', 'Shrug straight up, pause at top, control down.', 'Krč ramena přímo vzhůru, pauza nahoře, kontrolovaně dolů.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Russian Twist', 'Ruské otáčení (twist)', 'Core', 'Rotation', 'Bodyweight', 'Slight lean back, rotate through torso, control tempo.', 'Mírný záklon, otáčej trupem, kontroluj tempo.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Smith Machine Squat', 'Dřep na Smithově stroji', 'Quads', 'Squat', 'Smith', 'Feet slightly forward, flat back, controlled squat.', 'Chodidla mírně vpřed, záda rovná, kontrolovaný dřep.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Triceps Pushdown (rope)', 'Stahování kladky na triceps (lano)', 'Triceps', 'Isolation', 'Cable', 'Elbows pinned, extend fully and spread the rope.', 'Lokty u těla, propni dole a roztáhni lano.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Push Press', 'Tlak nad hlavu s dopomocí nohou (push press)', 'Front Delts', 'Vertical Push', 'Barbell', 'Slight dip, drive with legs, finish overhead with arms.', 'Lehký poddřep, prudce protlač nohama a dokonči pažemi.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Machine Shoulder Press', 'Tlak nad hlavu ve stroji', 'Front Delts', 'Vertical Push', 'Machine', 'Handles at shoulder height, press smooth, control back.', 'Madla ve výši ramen, tlač plynule nahoru, kontroluj zpět.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Arnold Press', 'Arnoldův tlak', 'Front Delts', 'Vertical Push', 'Dumbbell', 'Start palms in, rotate wrists out as you press up.', 'Začni dlaněmi k sobě, při tlaku vytoč zápěstí ven.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Pec Deck', 'Peck-deck (stroj na prsa)', 'Chest', 'Isolation', 'Machine', 'Elbows at chest height, drive pads together, controlled return.', 'Lokty ve výši hrudníku, sveď opěrky k sobě, kontrolovaný návrat.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Barbell Row', 'Veslování s velkou činkou v předklonu', 'Upper Back', 'Horizontal Pull', 'Barbell', 'Hinge ~45°, pull to lower ribs, squeeze the blades.', 'Předklon ~45°, tahni k dolním žebrům, stáhni lopatky.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Reverse Pec Deck', 'Obrácený peck-deck (zadní delty)', 'Rear Delts', 'Isolation', 'Machine', 'Chest on pad, open arms back, squeeze the blades.', 'Hrudník o opěrku, rozpažuj vzad, stáhni lopatky.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Pallof Press', 'Pallof press (anti-rotace)', 'Core', 'Rotation', 'Cable', 'Cable from the side, press hands out, resist rotation.', 'Kladka z boku, vytlač ruce před tělo, odolej rotaci.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Leg Press Calf Raise', 'Výpony na leg-pressu', 'Calves', 'Isolation', 'Machine', 'Toes on platform edge, press through toes, full range.', 'Špičky na okraji plošiny, tlač přes prsty, plný rozsah.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Crunch', 'Zkracovačky', 'Core', 'Core', 'Bodyweight', 'Lift shoulder blades, crunch abs, low back down.', 'Zvedej lopatky, krč břicho, bedra na zemi.');
insert into exercises (name_en, name_cz, primary_muscle, movement, equipment, cue_en, cue_cz) values ('Reverse Wrist Curl', 'Zdvih zápěstí nadhmatem (extenze)', 'Forearms', 'Isolation', 'Dumbbell', 'Overhand, raise the backs of hands, controlled.', 'Nadhmat, zvedej hřbety rukou vzhůru, kontrolovaně.');

-- =====================================================================
--  NOTE: reference libraries (meal_plan_library, supplement_library)
--  come in a small follow-on file (004_libraries.sql). Disposable test
--  substructure (programs, program_exercises, check_ins, meal/supplement
--  plans) is intentionally NOT migrated — rebuild in-app during testing.
-- =====================================================================

-- Quick verification (run as separate SELECTs after the inserts above):
--   select count(*) from coaches;    -- expect 1 (you, platform_admin)
--   select count(*) from clients;    -- expect 8 (all is_test = true)
--   select count(*) from exercises;  -- expect 107
